# Generated by Django 5.0.1 on 2024-01-27 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank_card',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='card_expiration_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_card_back',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_card_front',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='main_card',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_photo_back',
            field=models.ImageField(help_text='Şəxsiyyət vəsiqəsi 2', null=True, upload_to='id_photo/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_photo_front',
            field=models.ImageField(help_text='Şəxsiyyət vəsiqəsi', null=True, upload_to='id_photo/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='documents',
            field=models.FileField(help_text='Istifadəçi sənədləri', upload_to='user_documents/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='CardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_card', models.CharField(max_length=16)),
                ('main_card', models.BooleanField(default=True)),
                ('card_expiration_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=16)),
                ('is_activated', models.BooleanField(default=False)),
                ('safe_devices', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
